[package]
name = "anathema-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
anathema-geometry = { path = "../anathema-geometry" }
anathema-debug = { path = "../anathema-debug" }
anathema-default-widgets = { path = "../anathema-default-widgets" }
anathema-backend = { path = "../anathema-backend" }
anathema-state = { path = "../anathema-state" }
anathema-store = { path = "../anathema-store" }
anathema-templates = { path = "../anathema-templates" }
anathema-widgets = { path = "../anathema-widgets" }
flume = { workspace = true }
notify = { workspace = true }

[lints]
workspace = true
