[package]
name = "anathema-state-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
manyhow = "0.10.4"
quote = "1.0.35"
quote-use = "0.8.0"
syn = "2.0.48"

[lints]
workspace = true
